[2019-02-24 14:37:36.992][restartedMain][WARN][org.springframework.context.support.AbstractApplicationContext][556]:Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleController': Unsatisfied dependency expressed through field 'uservice'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'classDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'classificationDao' defined in file [C:\gysgong\waikuai_git\qinzhijie\qinZhiJie\target\classes\com\qzj\dao\ClassificationDao.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2019-02-24 14:40:23.007][restartedMain][WARN][org.springframework.context.support.AbstractApplicationContext][556]:Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleController': Unsatisfied dependency expressed through field 'uservice'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'classDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'classificationDao' defined in file [C:\gysgong\waikuai_git\qinzhijie\qinZhiJie\target\classes\com\qzj\dao\ClassificationDao.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2019-02-24 14:44:41.376][https-jsse-nio-20880-exec-8][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: java.lang.NullPointerException
[2019-02-24 17:50:07.700][https-jsse-nio-20880-exec-10][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: java.lang.NullPointerException
[2019-02-24 17:51:14.833][https-jsse-nio-20880-exec-3][WARN][org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver][411]:Failed to invoke @ExceptionHandler method: public com.qzj.commos.vo.ResponseData<java.lang.Object> com.qzj.commos.aop.ExceptionResolver.resolveThrowable(java.lang.Throwable)
java.lang.NullPointerException: null
	at org.springframework.web.util.UrlPathHelper.removeJsessionid(UrlPathHelper.java:517) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.util.UrlPathHelper.removeSemicolonContent(UrlPathHelper.java:502) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.util.UrlPathHelper.decodeAndCleanUriString(UrlPathHelper.java:435) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.util.UrlPathHelper.getOriginatingRequestUri(UrlPathHelper.java:382) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.addContentDispositionHeader(AbstractMessageConverterMethodProcessor.java:409) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:270) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:180) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:400) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:136) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:78) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1255) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1062) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) [spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.1.9.jar:1.1.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[2019-02-24 17:51:26.381][https-jsse-nio-20880-exec-5][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 17:52:33.696][https-jsse-nio-20880-exec-3][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 17:53:44.820][https-jsse-nio-20880-exec-10][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 17:58:05.721][https-jsse-nio-20880-exec-1][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 17:59:02.388][https-jsse-nio-20880-exec-7][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 18:08:43.007][https-jsse-nio-20880-exec-10][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sun Feb 24 18:08:41 CST 2019
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sun Feb 24 18:08:41 CST 2019
[2019-02-24 18:14:18.058][https-jsse-nio-20880-exec-5][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sun Feb 24 18:14:16 CST 2019
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Sun Feb 24 18:14:16 CST 2019
[2019-02-24 18:15:53.051][https-jsse-nio-20880-exec-5][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 18:19:08.165][https-jsse-nio-20880-exec-3][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 18:33:24.818][https-jsse-nio-20880-exec-4][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLException: Column count doesn't match value count at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(        bookId,            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(        ?,            ?,            ?,                ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Column count doesn't match value count at row 1
; bad SQL grammar []; nested exception is java.sql.SQLException: Column count doesn't match value count at row 1
[2019-02-24 19:00:04.555][https-jsse-nio-20880-exec-6][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: java.lang.NumberFormatException: For input string: ""
[2019-02-24 21:32:14.616][https-jsse-nio-20880-exec-8][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(        bookId,            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(        ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
; uncategorized SQLException; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
[2019-02-24 21:34:34.340][https-jsse-nio-20880-exec-9][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(        bookId,            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(        ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
; uncategorized SQLException; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
[2019-02-24 21:37:26.964][https-jsse-nio-20880-exec-4][WARN][org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][194]:Resolved exception caused by handler execution: org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
### The error may involve com.qzj.dao.BookDetailDao.add-Inline
### The error occurred while setting parameters
### SQL: insert into t_book_detail(        bookId,            partName,             dirPath,             orderNum,               createBy,            createTime,            updateTime,            updateBy       )   values(        ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?       )
### Cause: java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
; uncategorized SQLException; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\xA7\xAF\x9E\xE6\xB3...' for column 'partName' at row 1
